name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: 77.232.132.219
          username: root
          password: b^REx46-UL-mCx
          script: |
            cd /root/whatsapp_supplier_bot
            git pull
            npm install
            pm2 restart whatsapp-bot 